# Generated by Django 2.1.8 on 2020-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '文章标签', 'verbose_name_plural': '文章标签'},
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(db_column='cover_image', upload_to='article_img/%Y/%m/%d', verbose_name='图片'),
        ),
    ]
