# Generated by Django 2.1.8 on 2020-05-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_auto_20200528_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_on',
            field=models.DateTimeField(auto_now=True, db_column='created_on'),
        ),
    ]
