# Generated by Django 2.1.8 on 2020-05-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_auto_20200529_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
